spring:
  datasource:
    url: jdbc:mysql://3.34.47.175:3306/yetta
    username: root
    password: Hyundai!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
